### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Dhroov7** [coding-blocks/trouble-maker-frontend#6]
![screen shot 2018-08-11 at 6 28 44 pm](https://user-images.githubusercontent.com/18377905/43991968-708b76b8-9d66-11e8-828f-0991687e6b84.png)
![screen shot 2018-08-11 at 6 28 48 pm](https://user-images.githubusercontent.com/18377905/43991969-70c43a34-9d66-11e8-8491-b5ff36ce2f9a.png)
![screen shot 2018-08-11 at 6 28 52 pm](https://user-images.githubusercontent.com/18377905/43991970-70f0a5c4-9d66-11e8-9054-d0373851d85b.png)
![screen shot 2018-08-11 at 6 29 00 pm](https://user-images.githubusercontent.com/18377905/43991971-711c1876-9d66-11e8-9dac-b4d314692c41.png)
![screen shot 2018-08-11 at 6 28 58 pm](https://user-images.githubusercontent.com/18377905/43991972-714b39b2-9d66-11e8-9ea2-450ac7848ccb.png)
![screen shot 2018-08-11 at 6 28 55 pm](https://user-images.githubusercontent.com/18377905/43991973-71767e74-9d66-11e8-8235-a0c9b757fd83.png)

**Comment by Dhroov7** [comment]
@abhishek97 please review. #7

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 done in #9 

I forgot to push all the commits before, done in commit 8d8d48a2111e00c71c48cde0ae3b810b272bc00f

**Comment by abhishek97** [comment]
Merged in #7 .
